In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
merchant_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\merchant_db.csv")

In [3]:
merchant_df

,merchant_id,merchant_name,expected_category,avg_transaction_value,risk_level
0,M001,Starbucks,Food & Beverage,300,low
1,M002,Amazon,Shopping,1500,medium
2,M003,Flipkart,E-commerce,1200,medium
3,M004,Big Bazaar,Grocery,800,low
4,M005,OLA,Transport,200,low
5,M006,DMart,Grocery,1000,low
6,M007,Local Shop,NaN,100,high
7,M008,Apple,Electronics,25000,medium
8,M009,Swiggy,Food & Beverage,400,low
9,M010,Unknown Store,???,500,high

Assumptions:

- We don't know store means 
- That is the Local Store

## 1

In [7]:
merchant_df.loc[merchant_df['merchant_name'] == "Unknown Store"]

,merchant_id,merchant_name,expected_category,avg_transaction_value,risk_level
9,M010,Unknown Store,???,500,high

In [8]:
merchant_df['merchant_name'] = merchant_df['merchant_name'].replace('Unknown Store', 'Local Shop')

In [9]:
merchant_df

,merchant_id,merchant_name,expected_category,avg_transaction_value,risk_level
0,M001,Starbucks,Food & Beverage,300,low
1,M002,Amazon,Shopping,1500,medium
2,M003,Flipkart,E-commerce,1200,medium
3,M004,Big Bazaar,Grocery,800,low
4,M005,OLA,Transport,200,low
5,M006,DMart,Grocery,1000,low
6,M007,Local Shop,NaN,100,high
7,M008,Apple,Electronics,25000,medium
8,M009,Swiggy,Food & Beverage,400,low
9,M010,Local Shop,???,500,high

## 2

In [11]:
merchant_df['expected_category'] = merchant_df['expected_category'].replace({'???': 'Others', 'NaN': 'Others'})

In [14]:
merchant_df['expected_category'] = merchant_df['expected_category'].fillna('Others')

In [15]:
merchant_df

,merchant_id,merchant_name,expected_category,avg_transaction_value,risk_level
0,M001,Starbucks,Food & Beverage,300,low
1,M002,Amazon,Shopping,1500,medium
2,M003,Flipkart,E-commerce,1200,medium
3,M004,Big Bazaar,Grocery,800,low
4,M005,OLA,Transport,200,low
5,M006,DMart,Grocery,1000,low
6,M007,Local Shop,Others,100,high
7,M008,Apple,Electronics,25000,medium
8,M009,Swiggy,Food & Beverage,400,low
9,M010,Local Shop,Others,500,high

## 3 Label Encoding

In [20]:
merchant_df['risk_level_encoded'] = merchant_df['risk_level'].replace({'low': 1, 'medium': 2, 'high': 3})

C:\Users\Rudra\AppData\Local\Temp\ipykernel_2176\356277347.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merchant_df['risk_level_encoded'] = merchant_df['risk_level'].replace({'low': 1, 'medium': 2, 'high': 3})

In [21]:
merchant_df

,merchant_id,merchant_name,expected_category,avg_transaction_value,risk_level,risk_level_encoded
0,M001,Starbucks,Food & Beverage,300,low,1
1,M002,Amazon,Shopping,1500,medium,2
2,M003,Flipkart,E-commerce,1200,medium,2
3,M004,Big Bazaar,Grocery,800,low,1
4,M005,OLA,Transport,200,low,1
5,M006,DMart,Grocery,1000,low,1
6,M007,Local Shop,Others,100,high,3
7,M008,Apple,Electronics,25000,medium,2
8,M009,Swiggy,Food & Beverage,400,low,1
9,M010,Local Shop,Others,500,high,3