In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [2]:
fin_txn_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\finance_transactions.csv")
fraud_pattern_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\fraud_patterns.csv")
merchant_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\merchant_db.csv")
user_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\bronze\user_db.csv")

In [4]:
fraud_pattern_df

  pattern_id       merchant amount_range  fraud_flag
0       P001     Big Bazaar        >5000           1
1       P002         Amazon          <50           0
2       P003  Unknown Store          any           1
3       P004       Flipkart       >10000           1
4       P005            OLA        >1000           0
5       P006            NaN       >20000           1

In [6]:
fraud_pattern_df['merchant'] = fraud_pattern_df['merchant'].fillna('Unknown Store')

In [10]:
fraud_pattern_df['amount_range'] = fraud_pattern_df['amount_range'].replace({'any': '>20000'})

In [11]:
fraud_pattern_df

  pattern_id       merchant amount_range  fraud_flag
0       P001     Big Bazaar        >5000           1
1       P002         Amazon          <50           0
2       P003  Unknown Store       >20000           1
3       P004       Flipkart       >10000           1
4       P005            OLA        >1000           0
5       P006  Unknown Store       >20000           1