In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
SILVER_PATH = r"data/silver"
GOLD_PATH = r"data/gold"

os.makedirs(GOLD_PATH, exist_ok=True)

In [6]:
fin_txn_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\silver\finance_transactions_clean.csv")
user_df = pd.read_csv(r"C:\Users\Rudra\Desktop\smart-transaction-ledger\data\silver\user_db_clean.csv")

In [7]:
fin_txn_df

,transaction_id,user_id,date,amount,merchant_name,payment_mode,category,user_category_new,clean_brand,is_refund
0,TXN0001,U038,2024-03-11,6614.32,Starbucks,UPI,other,Low,Starbucks,0
1,TXN0002,U033,2024-01-31,14567.58,Amazon,Cash,refund,Medium-Low,Amazon,1
2,TXN0003,U013,2024-01-13,12937.22,Local Shop,UPI,shopping,Medium-Low,Local Shop,0
3,TXN0004,U026,2024-02-13,5755.79,Starbucks,Card,shopping,Low,Starbucks,0
4,TXN0005,U036,2024-01-13,29978.48,Apple,UPI,refund,High,Apple,1
...,...,...,...,...,...,...,...,...,...,...
995,TXN0996,U047,2024-01-19,20953.27,DMart,UPI,food,Medium-High,DMart,0
996,TXN0997,U018,2024-03-16,24817.09,OLA,Card,Food & Beverage,High,OLA,0
997,TXN0998,U029,2024-01-06,11386.02,Local Shop,Card,NaN,Medium-Low,Local Shop,0
998,TXN0999,U002,2024-03-18,27224.41,DMart,Card,Food & Beverage,High,DMart,0
999,TXN1000,U047,2024-01-08,11649.44,Local Shop,Card,electronics,Medium-Low,Local Shop,0

In [9]:
user_df

   user_id  city  spending_limit income_range_clean  risk_score_new
0     U001  BSSR         10000.0          Under 45k             0.1
1     U002  BBSR         15000.0          Over 100k             0.5
2     U003  BBSR         10000.0          Under 45k             0.5
3     U004  BSSR         10000.0          50k - 70k             0.5
4     U005  BSSR         50000.0          Over 100k             0.5
5     U006  BBSR         10000.0          70k - 90k             0.5
6     U007   CTC         50000.0          Over 100k             0.1
7     U008  BBSR         10000.0          50k - 70k             0.5
8     U009  BSSR         15000.0          Under 45k             0.5
9     U010  BSSR         10000.0          Under 45k             0.5
10    U011  BSSR         20000.0          50k - 70k             0.1
11    U012   CTC         50000.0          50k - 70k             0.1
12    U013  BSSR         50000.0          45k - 55k             0.1
13    U014  BSSR         20000.0          Under 45k             0.3
14    U015  BSSR         10000.0          Under 45k             0.3
15    U016  BSSR         15000.0          Under 45k             0.3
16    U017  BSSR         25000.0          45k - 55k             0.3
17    U018  BSSR         20000.0          Over 100k             0.1
18    U019  BSSR         10000.0          Under 45k             0.1
19    U020  BBSR         50000.0          70k - 90k             0.1
20    U021   CTC         25000.0          Over 100k             0.1
21    U022   CTC         15000.0          Under 45k             0.3
22    U023  BBSR         10000.0          50k - 70k             0.3
23    U024  BSSR         10000.0          45k - 55k             0.1
24    U025  BSSR         15000.0          70k - 90k             0.1
25    U026   CTC         15000.0          45k - 55k             0.1
26    U027  BBSR         10000.0          Over 100k             0.1
27    U028  BBSR         25000.0          Under 45k             0.5
28    U029  BBSR         15000.0          Under 45k             0.5
29    U030  BSSR         10000.0          50k - 70k             0.5
30    U031  BBSR         10000.0          Under 45k             0.5
31    U032  BSSR         25000.0          70k - 90k             0.5
32    U033   CTC         50000.0          70k - 90k             0.1
33    U034  BSSR         10000.0          70k - 90k             0.3
34    U035  BSSR         20000.0          Under 45k             0.3
35    U036  BSSR         25000.0          50k - 70k             0.1
36    U037  BSSR         10000.0          45k - 55k             0.1
37    U038  BBSR         50000.0          70k - 90k             0.5
38    U039  BSSR         10000.0          Under 45k             0.5
39    U040  BSSR         15000.0          Over 100k             0.5
40    U041  BSSR         25000.0          70k - 90k             0.5
41    U042  BSSR         20000.0          50k - 70k             0.5
42    U043  BBSR         50000.0          50k - 70k             0.5
43    U044   CTC         10000.0          50k - 70k             0.5
44    U045   CTC         50000.0          Over 100k             0.5
45    U046   CTC         50000.0          Under 45k             0.5
46    U047   CTC         10000.0          Over 100k             0.3
47    U048  BSSR         25000.0          Under 45k             0.3
48    U049  BSSR         25000.0          45k - 55k             0.3
49    U050  BBSR         10000.0          Over 100k             0.3

In [8]:
df = fin_txn_df.merge(user_df, on='user_id', how='left')


df['date'] = pd.to_datetime(df['date'])
df['day'] = df['date'].dt.date
df['weekday'] = df['date'].dt.weekday
df['is_weekend'] = df['weekday'].isin([5, 6]).astype(int)

In [11]:
df

,transaction_id,user_id,date,amount,merchant_name,payment_mode,category,user_category_new,clean_brand,is_refund,city,spending_limit,income_range_clean,risk_score_new,day,weekday,is_weekend
0,TXN0001,U038,2024-03-11,6614.32,Starbucks,UPI,other,Low,Starbucks,0,BBSR,50000.0,70k - 90k,0.5,2024-03-11,0,0
1,TXN0002,U033,2024-01-31,14567.58,Amazon,Cash,refund,Medium-Low,Amazon,1,CTC,50000.0,70k - 90k,0.1,2024-01-31,2,0
2,TXN0003,U013,2024-01-13,12937.22,Local Shop,UPI,shopping,Medium-Low,Local Shop,0,BSSR,50000.0,45k - 55k,0.1,2024-01-13,5,1
3,TXN0004,U026,2024-02-13,5755.79,Starbucks,Card,shopping,Low,Starbucks,0,CTC,15000.0,45k - 55k,0.1,2024-02-13,1,0
4,TXN0005,U036,2024-01-13,29978.48,Apple,UPI,refund,High,Apple,1,BSSR,25000.0,50k - 70k,0.1,2024-01-13,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,TXN0996,U047,2024-01-19,20953.27,DMart,UPI,food,Medium-High,DMart,0,CTC,10000.0,Over 100k,0.3,2024-01-19,4,0
996,TXN0997,U018,2024-03-16,24817.09,OLA,Card,Food & Beverage,High,OLA,0,BSSR,20000.0,Over 100k,0.1,2024-03-16,5,1
997,TXN0998,U029,2024-01-06,11386.02,Local Shop,Card,NaN,Medium-Low,Local Shop,0,BBSR,15000.0,Under 45k,0.5,2024-01-06,5,1
998,TXN0999,U002,2024-03-18,27224.41,DMart,Card,Food & Beverage,High,DMart,0,BBSR,15000.0,Over 100k,0.5,2024-03-18,0,0
999,TXN1000,U047,2024-01-08,11649.44,Local Shop,Card,electronics,Medium-Low,Local Shop,0,CTC,10000.0,Over 100k,0.3,2024-01-08,0,0

In [13]:
user_agg = df.groupby('user_id').agg(

    # Spending Behavior
    total_spent=('amount', 'sum'),
    avg_transaction=('amount', 'mean'),
    max_transaction=('amount', 'max'),
    transaction_count=('transaction_id', 'count'),

    # Time Behavior
    active_days=('day', 'nunique'),
    weekend_spending=('amount', lambda x: x[df.loc[x.index, 'is_weekend'] == 1].sum()),

    # Payment Behavior
    upi_count=('payment_mode', lambda x: (x == 'UPI').sum()),
    cash_count=('payment_mode', lambda x: (x == 'Cash').sum()),

    # Category Behavior
    most_used_category=('category', lambda x: x.mode()[0] if not x.mode().empty else 'Unknown'),
    category_diversity=('category', 'nunique')

).reset_index()

In [14]:
user_agg

,user_id,total_spent,avg_transaction,max_transaction,transaction_count,active_days,weekend_spending,upi_count,cash_count,most_used_category,category_diversity
0,U001,255869.15,17057.943333,26500.75,15,15,350.40,7,3,Food & Beverage,7
1,U002,268640.66,13432.033000,27224.41,20,20,96501.03,9,5,Food & Beverage,8
2,U003,252994.33,13315.491053,29174.50,19,17,19659.72,5,10,refund,7
3,U004,385418.03,17519.001364,29232.21,22,18,79375.97,10,7,grocery,8
4,U005,283306.45,16665.085294,26715.76,17,14,54396.74,6,5,grocery,8
5,U006,384825.99,14800.999615,29678.83,26,23,38307.97,10,7,shopping,8
6,U007,399118.81,15350.723462,28512.44,26,23,112028.18,7,10,grocery,8
7,U008,328357.28,16417.864000,28382.11,20,15,97247.61,8,3,Food & Beverage,8
8,U009,403331.19,17536.138696,29712.06,23,19,77599.60,6,7,Food & Beverage,8
9,U010,249449.61,14673.506471,29098.01,17,17,108172.46,5,9,food,8
10,U011,284266.62,12921.210000,28694.43,22,19,49960.81,8,7,electronics,8
11,U012,380894.35,16560.623913,29785.77,23,19,103571.50,2,7,Food & Beverage,8
12,U013,403115.27,13437.175667,29259.53,30,24,110176.08,11,9,shopping,8
13,U014,301072.89,15053.644500,29696.44,20,17,120760.36,8,8,other,8
14,U015,147904.05,13445.822727,25605.08,11,11,67389.64,1,4,Food & Beverage,5
15,U016,306050.81,15302.540500,29015.22,20,18,99547.12,7,2,refund,7
16,U017,324417.89,18023.216111,29355.71,18,17,84137.28,4,8,Food & Beverage,8
17,U018,351362.80,19520.155556,29838.89,18,16,130571.06,5,5,Food & Beverage,6
18,U019,324399.41,14745.427727,29285.61,22,21,81837.18,10,6,shopping,7
19,U020,206035.61,12877.225625,29905.49,16,16,42182.98,3,9,refund,7
20,U021,368218.30,14162.242308,29091.79,26,24,81551.61,10,8,transport,8
21,U022,167085.77,12852.751538,21982.42,13,12,66745.80,3,6,food,7
22,U023,289260.48,13148.203636,28861.25,22,19,68069.10,11,5,grocery,7
23,U024,319290.86,15964.543000,29917.98,20,18,76650.25,7,8,shopping,7
24,U025,227265.92,13368.583529,27340.96,17,14,37332.60,6,5,transport,6
25,U026,294548.20,14026.104762,28470.83,21,20,89113.06,5,7,other,7
26,U027,445817.64,14860.588000,29869.97,30,26,74382.81,11,10,transport,8
27,U028,283411.67,14916.403684,27791.20,19,17,119525.69,5,10,Food & Beverage,7
28,U029,322365.70,13431.904167,27518.17,24,18,53351.00,8,4,electronics,7
29,U030,248374.53,12418.726500,26939.40,20,18,78536.82,5,8,shopping,5
30,U031,249733.48,11351.521818,25783.64,22,20,65553.81,6,6,Food & Beverage,7
31,U032,253062.32,14886.018824,27362.36,17,17,52142.92,5,7,Food & Beverage,7
32,U033,209988.37,13999.224667,25791.57,15,15,97477.06,4,7,food,7
33,U034,299630.06,14981.503000,26906.96,20,18,31068.60,8,4,electronics,7
34,U035,193801.89,13842.992143,28941.12,14,14,22321.28,5,4,grocery,7
35,U036,245736.60,12933.505263,29978.48,19,18,105734.46,10,7,Food & Beverage,8
36,U037,357518.65,16250.847727,29640.31,22,20,126313.55,4,11,food,8
37,U038,238334.50,10362.369565,26065.68,23,20,101821.41,4,7,other,7
38,U039,288465.77,14423.288500,24580.84,20,19,70092.37,6,5,food,7
39,U040,191892.34,13706.595714,28360.21,14,13,64951.40,5,4,other,7
40,U041,333965.79,16698.289500,29710.94,20,19,155071.47,9,6,Food & Beverage,8
41,U042,292506.04,15395.054737,29129.48,19,17,34760.47,9,4,Food & Beverage,8
42,U043,258262.94,16141.433750,27926.59,16,15,93881.82,3,7,electronics,6
43,U044,350210.79,14592.116250,29961.71,24,23,122392.35,9,7,grocery,8
44,U045,311239.62,14820.934286,29828.55,21,19,107802.68,5,7,grocery,7
45,U046,417794.11,17408.087917,28771.45,24,24,115352.00,8,5,grocery,8
46,U047,275814.01,17238.375625,27206.57,16,15,51710.84,3,5,Food & Beverage,8
47,U048,384062.55,14771.636538,28887.17,26,25,96946.63,8,13,shopping,8
48,U049,186695.58,10371.976667,29165.22,18,16,25731.72,8,6,food,8
49,U050,192234.39,14787.260769,29249.42,13,12,19389.79,4,6,refund,7

In [15]:
# Spending per day
user_agg['spending_per_day'] = user_agg['total_spent'] / user_agg['active_days']

# Payment ratios
user_agg['upi_ratio'] = user_agg['upi_count'] / user_agg['transaction_count']
user_agg['cash_ratio'] = user_agg['cash_count'] / user_agg['transaction_count']

# Merge back user info
user_agg = user_agg.merge(user_df, on='user_id', how='left')

In [21]:
user_agg.columns.tolist()

['user_id',
 'total_spent',
 'avg_transaction',
 'max_transaction',
 'transaction_count',
 'active_days',
 'weekend_spending',
 'upi_count',
 'cash_count',
 'most_used_category',
 'category_diversity',
 'spending_per_day',
 'upi_ratio',
 'cash_ratio',
 'city',
 'spending_limit',
 'income_range_clean',
 'risk_score_new']

In [16]:
user_agg

,user_id,total_spent,avg_transaction,max_transaction,transaction_count,active_days,weekend_spending,upi_count,cash_count,most_used_category,category_diversity,spending_per_day,upi_ratio,cash_ratio,city,spending_limit,income_range_clean,risk_score_new
0,U001,255869.15,17057.943333,26500.75,15,15,350.40,7,3,Food & Beverage,7,17057.943333,0.466667,0.200000,BSSR,10000.0,Under 45k,0.1
1,U002,268640.66,13432.033000,27224.41,20,20,96501.03,9,5,Food & Beverage,8,13432.033000,0.450000,0.250000,BBSR,15000.0,Over 100k,0.5
2,U003,252994.33,13315.491053,29174.50,19,17,19659.72,5,10,refund,7,14882.019412,0.263158,0.526316,BBSR,10000.0,Under 45k,0.5
3,U004,385418.03,17519.001364,29232.21,22,18,79375.97,10,7,grocery,8,21412.112778,0.454545,0.318182,BSSR,10000.0,50k - 70k,0.5
4,U005,283306.45,16665.085294,26715.76,17,14,54396.74,6,5,grocery,8,20236.175000,0.352941,0.294118,BSSR,50000.0,Over 100k,0.5
5,U006,384825.99,14800.999615,29678.83,26,23,38307.97,10,7,shopping,8,16731.564783,0.384615,0.269231,BBSR,10000.0,70k - 90k,0.5
6,U007,399118.81,15350.723462,28512.44,26,23,112028.18,7,10,grocery,8,17352.991739,0.269231,0.384615,CTC,50000.0,Over 100k,0.1
7,U008,328357.28,16417.864000,28382.11,20,15,97247.61,8,3,Food & Beverage,8,21890.485333,0.400000,0.150000,BBSR,10000.0,50k - 70k,0.5
8,U009,403331.19,17536.138696,29712.06,23,19,77599.60,6,7,Food & Beverage,8,21227.957368,0.260870,0.304348,BSSR,15000.0,Under 45k,0.5
9,U010,249449.61,14673.506471,29098.01,17,17,108172.46,5,9,food,8,14673.506471,0.294118,0.529412,BSSR,10000.0,Under 45k,0.5
10,U011,284266.62,12921.210000,28694.43,22,19,49960.81,8,7,electronics,8,14961.401053,0.363636,0.318182,BSSR,20000.0,50k - 70k,0.1
11,U012,380894.35,16560.623913,29785.77,23,19,103571.50,2,7,Food & Beverage,8,20047.071053,0.086957,0.304348,CTC,50000.0,50k - 70k,0.1
12,U013,403115.27,13437.175667,29259.53,30,24,110176.08,11,9,shopping,8,16796.469583,0.366667,0.300000,BSSR,50000.0,45k - 55k,0.1
13,U014,301072.89,15053.644500,29696.44,20,17,120760.36,8,8,other,8,17710.170000,0.400000,0.400000,BSSR,20000.0,Under 45k,0.3
14,U015,147904.05,13445.822727,25605.08,11,11,67389.64,1,4,Food & Beverage,5,13445.822727,0.090909,0.363636,BSSR,10000.0,Under 45k,0.3
15,U016,306050.81,15302.540500,29015.22,20,18,99547.12,7,2,refund,7,17002.822778,0.350000,0.100000,BSSR,15000.0,Under 45k,0.3
16,U017,324417.89,18023.216111,29355.71,18,17,84137.28,4,8,Food & Beverage,8,19083.405294,0.222222,0.444444,BSSR,25000.0,45k - 55k,0.3
17,U018,351362.80,19520.155556,29838.89,18,16,130571.06,5,5,Food & Beverage,6,21960.175000,0.277778,0.277778,BSSR,20000.0,Over 100k,0.1
18,U019,324399.41,14745.427727,29285.61,22,21,81837.18,10,6,shopping,7,15447.590952,0.454545,0.272727,BSSR,10000.0,Under 45k,0.1
19,U020,206035.61,12877.225625,29905.49,16,16,42182.98,3,9,refund,7,12877.225625,0.187500,0.562500,BBSR,50000.0,70k - 90k,0.1
20,U021,368218.30,14162.242308,29091.79,26,24,81551.61,10,8,transport,8,15342.429167,0.384615,0.307692,CTC,25000.0,Over 100k,0.1
21,U022,167085.77,12852.751538,21982.42,13,12,66745.80,3,6,food,7,13923.814167,0.230769,0.461538,CTC,15000.0,Under 45k,0.3
22,U023,289260.48,13148.203636,28861.25,22,19,68069.10,11,5,grocery,7,15224.235789,0.500000,0.227273,BBSR,10000.0,50k - 70k,0.3
23,U024,319290.86,15964.543000,29917.98,20,18,76650.25,7,8,shopping,7,17738.381111,0.350000,0.400000,BSSR,10000.0,45k - 55k,0.1
24,U025,227265.92,13368.583529,27340.96,17,14,37332.60,6,5,transport,6,16233.280000,0.352941,0.294118,BSSR,15000.0,70k - 90k,0.1
25,U026,294548.20,14026.104762,28470.83,21,20,89113.06,5,7,other,7,14727.410000,0.238095,0.333333,CTC,15000.0,45k - 55k,0.1
26,U027,445817.64,14860.588000,29869.97,30,26,74382.81,11,10,transport,8,17146.832308,0.366667,0.333333,BBSR,10000.0,Over 100k,0.1
27,U028,283411.67,14916.403684,27791.20,19,17,119525.69,5,10,Food & Beverage,7,16671.274706,0.263158,0.526316,BBSR,25000.0,Under 45k,0.5
28,U029,322365.70,13431.904167,27518.17,24,18,53351.00,8,4,electronics,7,17909.205556,0.333333,0.166667,BBSR,15000.0,Under 45k,0.5
29,U030,248374.53,12418.726500,26939.40,20,18,78536.82,5,8,shopping,5,13798.585000,0.250000,0.400000,BSSR,10000.0,50k - 70k,0.5
30,U031,249733.48,11351.521818,25783.64,22,20,65553.81,6,6,Food & Beverage,7,12486.674000,0.272727,0.272727,BBSR,10000.0,Under 45k,0.5
31,U032,253062.32,14886.018824,27362.36,17,17,52142.92,5,7,Food & Beverage,7,14886.018824,0.294118,0.411765,BSSR,25000.0,70k - 90k,0.5
32,U033,209988.37,13999.224667,25791.57,15,15,97477.06,4,7,food,7,13999.224667,0.266667,0.466667,CTC,50000.0,70k - 90k,0.1
33,U034,299630.06,14981.503000,26906.96,20,18,31068.60,8,4,electronics,7,16646.114444,0.400000,0.200000,BSSR,10000.0,70k - 90k,0.3
34,U035,193801.89,13842.992143,28941.12,14,14,22321.28,5,4,grocery,7,13842.992143,0.357143,0.285714,BSSR,20000.0,Under 45k,0.3
35,U036,245736.60,12933.505263,29978.48,19,18,105734.46,10,7,Food & Beverage,8,13652.033333,0.526316,0.368421,BSSR,25000.0,50k - 70k,0.1
36,U037,357518.65,16250.847727,29640.31,22,20,126313.55,4,11,food,8,17875.932500,0.181818,0.500000,BSSR,10000.0,45k - 55k,0.1
37,U038,238334.50,10362.369565,26065.68,23,20,101821.41,4,7,other,7,11916.725000,0.173913,0.304348,BBSR,50000.0,70k - 90k,0.5
38,U039,288465.77,14423.288500,24580.84,20,19,70092.37,6,5,food,7,15182.408947,0.300000,0.250000,BSSR,10000.0,Under 45k,0.5
39,U040,191892.34,13706.595714,28360.21,14,13,64951.40,5,4,other,7,14760.949231,0.357143,0.285714,BSSR,15000.0,Over 100k,0.5
40,U041,333965.79,16698.289500,29710.94,20,19,155071.47,9,6,Food & Beverage,8,17577.146842,0.450000,0.300000,BSSR,25000.0,70k - 90k,0.5
41,U042,292506.04,15395.054737,29129.48,19,17,34760.47,9,4,Food & Beverage,8,17206.237647,0.473684,0.210526,BSSR,20000.0,50k - 70k,0.5
42,U043,258262.94,16141.433750,27926.59,16,15,93881.82,3,7,electronics,6,17217.529333,0.187500,0.437500,BBSR,50000.0,50k - 70k,0.5
43,U044,350210.79,14592.116250,29961.71,24,23,122392.35,9,7,grocery,8,15226.556087,0.375000,0.291667,CTC,10000.0,50k - 70k,0.5
44,U045,311239.62,14820.934286,29828.55,21,19,107802.68,5,7,grocery,7,16381.032632,0.238095,0.333333,CTC,50000.0,Over 100k,0.5
45,U046,417794.11,17408.087917,28771.45,24,24,115352.00,8,5,grocery,8,17408.087917,0.333333,0.208333,CTC,50000.0,Under 45k,0.5
46,U047,275814.01,17238.375625,27206.57,16,15,51710.84,3,5,Food & Beverage,8,18387.600667,0.187500,0.312500,CTC,10000.0,Over 100k,0.3
47,U048,384062.55,14771.636538,28887.17,26,25,96946.63,8,13,shopping,8,15362.502000,0.307692,0.500000,BSSR,25000.0,Under 45k,0.3
48,U049,186695.58,10371.976667,29165.22,18,16,25731.72,8,6,food,8,11668.473750,0.444444,0.333333,BSSR,25000.0,45k - 55k,0.3
49,U050,192234.39,14787.260769,29249.42,13,12,19389.79,4,6,refund,7,16019.532500,0.307692,0.461538,BBSR,10000.0,Over 100k,0.3